name: Deploy to Prod

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: "npm"
      - name: Install Dependencies'
        run: npm ci
      - name: Deploy to Heroku
        uses: AkhileshNS/heroku-deploy@v3.12.13
        with:
          heroku_api_key: ${{secrets.HEROKU_PROD_API_KEY}}
          heroku_app_name: "lahiki-recruit-frontend"
          heroku_email: "eddine.farid@hotmail.fr"
